queue_rules:
  - name: default
    batch_size: 3
    allow_inplace_checks: true
    merge_conditions:
      - label=go
pull_request_rules:
  - name: q
    conditions:
      - base=main
      - label=queueme
    actions:
      queue:
        name: default
