pull_request_rules:
  - name: copyssti
    conditions:
      - base=main
      - title~=COPYSSTI
    actions:
      copy:
        branches:
          - staging
        title: "copied [{{ title }}] body[{{ body }}]"
  - name: labelssti
    conditions:
      - base=main
      - title~=COPYSSTI
    actions:
      label:
        add:
          - "lbl-{{ body }}"
